import { NextRequest, NextResponse } from "next/server";

/**
 * POST /api/assistant
 *
 * Mock endpoint for the AI Assistant chat tool. Accepts a prompt (and
 * optional chat history) and returns a simulated Gemini-style reply.
 *
 * TODO: Replace the mock logic below with a real call to Vertex AI Gemini:
 *
 *   import { VertexAI } from "@google-cloud/vertexai";
 *   const vertexAI = new VertexAI({
 *     project: process.env.VERTEX_AI_PROJECT_ID,
 *     location: process.env.VERTEX_AI_LOCATION,
 *   });
 *   const model = vertexAI.getGenerativeModel({
 *     model: process.env.VERTEX_AI_GEMINI_MODEL || "gemini-1.5-pro",
 *   });
 *   const result = await model.generateContent(prompt);
 *   const text = result.response.candidates?.[0]?.content?.parts?.[0]?.text;
 */
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const prompt: string = body.prompt || body.message || "";

  if (!prompt.trim()) {
    return NextResponse.json({ error: "Prompt is required." }, { status: 400 });
  }

  // Simulate generation latency.
  await new Promise((resolve) => setTimeout(resolve, 400));

  const reply = `This is a mock response to: "${prompt}". In production, this will be generated by Vertex AI Gemini.`;

  return NextResponse.json({
    role: "assistant",
    content: reply,
    model: "gemini-1.5-pro (mock)",
    createdAt: new Date().toISOString(),
  });
}
